In [ ]:
# code starts here

In [7]:
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Function to load and preprocess image data
def load_images(image_dir, label):
    data = []
    labels = []
    for filename in os.listdir(image_dir):
        if filename.endswith(".jpg"):
            img = cv2.imread(os.path.join(image_dir, filename))
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # Convert to grayscale
            img = cv2.resize(img, (100, 100))  # Resize to a consistent size
            data.append(img.flatten())  # Flatten the image data converts 2D to 1D array
            labels.append(label)
    return data, labels

# Load and preprocess cat images
cat_data, cat_labels = load_images(r"C:\\Users\\AGM MSME PNB\\OneDrive\\Desktop\\Sashidhar\\Data scince\\Projects\\Final Project\\PROJECT-4 (IMAGE CLASSIFICATION)\\Data_set\\dataset\\training_set\\cats", 0)

# Load and preprocess dog images
dog_data, dog_labels = load_images(r"C:\\Users\\AGM MSME PNB\\OneDrive\\Desktop\\Sashidhar\\Data scince\\Projects\\Final Project\\PROJECT-4 (IMAGE CLASSIFICATION)\\Data_set\\dataset\\training_set\\dogs", 1)

# Combine data and labels
X = cat_data + dog_data
y = cat_labels + dog_labels

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Logistic Regression
Logistic_Regression= LogisticRegression()
Logistic_Regression.fit(X_train, y_train)

# SVM Classifier
svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)

#KNN Classifier
Knn_classifier = KNeighborsClassifier()
Knn_classifier.fit(X_train, y_train)

#Decision Tree
DecisionTree_classifier = DecisionTreeClassifier(criterion='entropy',max_depth=100)
DecisionTree_classifier.fit(X_train, y_train)


# Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

#  Adaboost Classifier
Ab_classifier = AdaBoostClassifier()
Ab_classifier.fit(X_train, y_train)

# Gradinet boost Classifier
Gb_classifier = GradientBoostingClassifier()
Gb_classifier.fit(X_train, y_train)



# Evaluate the models
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)
    return accuracy, conf_matrix, class_report

lr_accuracy, lr_conf_matrix, lr_class_report = evaluate_model(Logistic_Regression, X_test, y_test)
svm_accuracy, svm_conf_matrix, svm_class_report = evaluate_model(svm_classifier, X_test, y_test)
knn_accuracy, knn_conf_matrix, knn_class_report = evaluate_model(Knn_classifier, X_test, y_test)
decision_tree_accuracy, decision_tree_conf_matrix,decision_tree_class_report = evaluate_model(DecisionTree_classifier, X_test, y_test)
rf_accuracy, rf_conf_matrix, rf_class_report = evaluate_model(rf_classifier, X_test, y_test)
ab_accuracy, ab_conf_matrix, ab_class_report = evaluate_model(Ab_classifier, X_test, y_test)
gb_accuracy, gb_conf_matrix, gb_class_report = evaluate_model(Gb_classifier, X_test, y_test)


print("Logistic Regression Model:")
print("Accuracy:", lr_accuracy)
print("Confusion Matrix:\n", lr_conf_matrix)
print("Classification Report:\n", lr_class_report)

print("SVM Model:")
print("Accuracy:", svm_accuracy)
print("Confusion Matrix:\n", svm_conf_matrix)
print("Classification Report:\n", svm_class_report)

print("KNN Model:")
print("Accuracy:", knn_accuracy)
print("Confusion Matrix:\n", knn_conf_matrix)
print("Classification Report:\n", knn_class_report)

print("Decision Tree Model:")
print("Accuracy:", decision_tree_accuracy)
print("Confusion Matrix:\n", decision_tree_conf_matrix)
print("Classification Report:\n", decision_tree_class_report)


print("\nRandom Forest Model:")
print("Accuracy:", rf_accuracy)
print("Confusion Matrix:\n", rf_conf_matrix)
print("Classification Report:\n", rf_class_report)

print("\n Adaboost Forest Model:")
print("Accuracy:", ab_accuracy)
print("Confusion Matrix:\n", ab_conf_matrix)
print("Classification Report:\n", ab_class_report)

print("\nGradient Forest Model:")
print("Accuracy:", gb_accuracy)
print("Confusion Matrix:\n", gb_conf_matrix)
print("Classification Report:\n", gb_class_report)


Logistic Regression Model:
Accuracy: 0.5263157894736842
Confusion Matrix:
 [[5 7]
 [2 5]]
Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.42      0.53        12
           1       0.42      0.71      0.53         7

    accuracy                           0.53        19
   macro avg       0.57      0.57      0.53        19
weighted avg       0.60      0.53      0.53        19

SVM Model:
Accuracy: 0.42105263157894735
Confusion Matrix:
 [[ 2 10]
 [ 1  6]]
Classification Report:
               precision    recall  f1-score   support

           0       0.67      0.17      0.27        12
           1       0.38      0.86      0.52         7

    accuracy                           0.42        19
   macro avg       0.52      0.51      0.39        19
weighted avg       0.56      0.42      0.36        19

KNN Model:
Accuracy: 0.3684210526315789
Confusion Matrix:
 [[ 1 11]
 [ 1  6]]
Classification Report:
               precision    

In [ ]:
# code ends here 

descision tree and random forest have accuracy of around 0.57

In [ ]:
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Function to load and preprocess image data
def load_images(image_dir, label):
    data = []
    labels = []
    for filename in os.listdir(image_dir):
        if filename.endswith(".jpg"):
            img = cv2.imread(os.path.join(image_dir, filename))
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # Convert to grayscale
            img = cv2.resize(img, (100, 100))  # Resize to a consistent size
            data.append(img.flatten())  # Flatten the image data
            labels.append(label)
    return data, labels

# Load and preprocess cat images
cat_data, cat_labels = load_images(r"C:\\Users\\AGM MSME PNB\\OneDrive\\Desktop\\Sashidhar\\Data scince\\Projects\\Final Project\\PROJECT-4 (IMAGE CLASSIFICATION)\\Data_set\\dataset\\training_set\\cats", 0)

# Load and preprocess dog images
dog_data, dog_labels = load_images(r"C:\\Users\\AGM MSME PNB\\OneDrive\\Desktop\\Sashidhar\\Data scince\\Projects\\Final Project\\PROJECT-4 (IMAGE CLASSIFICATION)\\Data_set\\dataset\\training_set\\dogs", 1)

# Combine data and labels
X = cat_data + dog_data
y = cat_labels + dog_labels

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# SVM Classifier
svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)

# Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)



# Evaluate the models
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)
    return accuracy, conf_matrix, class_report

svm_accuracy, svm_conf_matrix, svm_class_report = evaluate_model(svm_classifier, X_test, y_test)
rf_accuracy, rf_conf_matrix, rf_class_report = evaluate_model(rf_classifier, X_test, y_test)

print("SVM Model:")
print("Accuracy:", svm_accuracy)
print("Confusion Matrix:\n", svm_conf_matrix)
print("Classification Report:\n", svm_class_report)

print("\nRandom Forest Model:")
print("Accuracy:", rf_accuracy)
print("Confusion Matrix:\n", rf_conf_matrix)
print("Classification Report:\n", rf_class_report)


In [ ]:
models=[LogisticRegression(),DecisionTreeClassifier(criterion='entropy',max_depth=100),KNeighborsClassifier()
       AdaBoostClassifier() , GradientBoostingClassifier() ]
